-- MySQL Script generated by MySQL Workbench
-- 2022年10月21日 (週五) 19時42分53秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hibernatedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hibernatedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hibernatedb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hibernatedb` ;

-- -----------------------------------------------------
-- Table `hibernatedb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernatedb`.`store` (
  `store_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` TIMESTAMP NULL DEFAULT NULL,
  `facebook` VARCHAR(100) NULL DEFAULT NULL,
  `googlemap` VARCHAR(100) NULL DEFAULT NULL,
  `instargram` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernatedb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernatedb`.`product` (
  `product_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` INT UNSIGNED NULL DEFAULT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `price` SMALLINT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `product_store_id_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `hibernatedb`.`store` (`store_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernatedb`.`product_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernatedb`.`product_list` (
  `product_list_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  INDEX `product_list_product_id_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `hibernatedb`.`product` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernatedb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernatedb`.`user` (
  `user_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `user_address` VARCHAR(100) NULL DEFAULT NULL,
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hibernatedb`.`order_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernatedb`.`order_list` (
  `user_id` INT UNSIGNED NOT NULL,
  `product_list_id` INT UNSIGNED NOT NULL,
  `note` VARCHAR(100) NULL DEFAULT NULL,
  `create_time` TIME NULL DEFAULT NULL,
  `is_complete` TINYINT NULL,
  INDEX `order_list_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `hibernatedb`.`user` (`user_id`),
  CONSTRAINT `fk_product_list_id`
    FOREIGN KEY (`product_list_id`)
    REFERENCES `hibernatedb`.`product_list` (`product_list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
