package com.backend.sever.user;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController    // This means that this class is a Controller

public class UserSignUpController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    //insert into user (email, latitude, longtitude, password, user_address, user_name) values (?, ?, ?, ?, ?, ?)
    @RequestMapping(path="user/signup", method = RequestMethod.POST)
    @ResponseBody
    public  void signup(@RequestBody Map<String,String> payload) {
        User n = new User();
        n.setUser_name(payload.get("userName"));
        n.setUser_address(payload.get("userAddress"));
        n.setEmail(payload.get("email"));
        n.setPassword(payload.get("password"));
        n.setLongtitude(Float.parseFloat(payload.get("longtitude")));
        n.setLatitude(Float.parseFloat(payload.get("latitude")));
        userRepository.save(n);
    }
}
