package com.backend.sever.store;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
public class StoreSignUpController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StoreRepository storeRepository;

    @RequestMapping(path="store/add") // Map ONLY POST Requests
    @ResponseBody
    public String addNewUser (
            @RequestParam String store_name,
            @RequestParam String address
    ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Store n = new Store();
        n.setStore_name(store_name);
        n.setAddress(address);
        storeRepository.save(n);
        return "Saved";
    }


    @RequestMapping(path="store/all")
    @ResponseBody
    public  Iterable<Store> findAll() {
        // This returns a JSON or XML with the users
        return storeRepository.findAll();
    }
}
